<?php
namespace xz1mefx\ufu\components;

use yii\base\Component;
use yii\helpers\ArrayHelper;

/**
 * Class UFU
 * @package xz1mefx\ufu\components
 */
class UFU extends Component
{

    public $categoryTypes = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public function getTypesIdList()
    {
        return ArrayHelper::getColumn($this->categoryTypes, 'id');
    }

    /**
     * @param $id
     *
     * @return string|null
     */
    public function getTypeNameById($id)
    {
        return ArrayHelper::getValue($this->getDrDownCategoryTypes(), $id);
    }

    /**
     * @return array
     */
    public function getDrDownCategoryTypes()
    {
        return ArrayHelper::map($this->categoryTypes, 'id', 'name');
    }

}
